config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "help" => "pages#help"
  get "create_stor_info" => "pages#create_stor_info"
  get "cart/add" =>"cart#add"
  get "cart/delete" =>"cart#delete"
  get "cart/delete_all" => "cart#delete_all"
  get "cart/show" =>"cart#show"
  get "clear" => "cart#clear"
  get "elsearch" => "search#elsearch"

  resources :orders do
    collection do
      get "vue_table"
    end
  end

  resources :payments, only: [] do
    # member do payments/:id/foo
    #   get "foo"
    # end
    collection do #payments/foo
      get "checkout"
      get "successful"
      post "execute"
    end
  end

  resources :stores do
    resources :products do
      resources :reviews
    end
  end

  namespace :manager do
    resources :stores do
      resources :orders do
        collection do
          get "statistic"
        end
      end
      resources :products do
        collection do
          get "export"
          get "import"
          post "post_import"
        end
      end
    end

    resources :products, only: [:index]
  end

  namespace :api do
    resources :stores, only: [:index, :show] do
      get "products"
      resources :products, only: [:show] do
        # collection do
        #   get "store_products"
        # end
      end
    end
    resources :products, only: [:index]
  end

  resources :products, only: [:index]
  resources :users

  root "home#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  belongs_to :store
  has_one :payment

  validates :name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :country, presence: true
  validates :zip, presence: true
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ManagerController
  def index
    status = params[:status]
    if status.nil?
      status = "new"
    end

    @store = Store.find(params[:store_id])
    @orders = @store.orders
    @orders = @orders.order(:created_at => :DESC)

    @orders = @orders.where(status: status)
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @products = @order.products
  end

  def statistic
    @store = Store.find(params[:store_id])
    @orders = @store.orders

    @data_keys = Array.new(7) do |i|
      date = Time.now - i.day
      date.strftime("%d.%m.%g")
    end
    @data_keys = @data_keys.reverse

    @data_values = Array.new(7) do |i|
      date = Time.now.to_date - i.day
      orders = @orders.where("DATE(created_at) = DATE(?)", date)
      orders = orders.count
    end
    @data_values = @data_values.reverse
  end

  def destroy
  end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController
  before_action :store
  include ExportProduct
  include ImportProduct

  def new
    @product = store.products.new
    @categories = Category.all
  end

  def create
    @product = store.products.create(product_params)

    if @product.save
      redirect_to manager_store_path(@store)
    else
      return render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @product = store.products.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = store.products.find(params[:id])

    if @product.update(product_params)
      redirect_to manager_store_path(@store)
    else
      render :edit
    end
  end

  def destroy
    @product = store.products.find(params[:id])
    @product.destroy
    redirect_to manager_store_path(@store)
  end

  def export
    export_product
  end

  def import
  end

  def post_import
    file = params[:file]
    file_data = file.read
    store_id = @store.id
    file_type = params[:file].content_type
    ImportProductJob.perform_later(file_type, file_data, store_id)
    redirect_to manager_store_path(@store.id), notice: "import in progress"
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :discount, { images: [] }, :category_id)
  end

  def store
    @store ||= current_user.stores.find(params[:store_id])
  end
end

app/controllers/manager/stores_controller.rb
class Manager::StoresController < ManagerController
  def index
    @stores = Store.where(:user_id => current_user.id)
  end

  def show
    @store = Store.find(params[:id])
  end

  def edit
    @store = current_user_store
  end

  def update
    @store = current_user_store

    if @store.update(store_params)
      redirect_to @store
    else
      render :edit
    end
  end

  def destroy
    @store = current_user_store
    @store.destroy

    redirect_to current_user
  end

  private

  def store_params
    params.require(:store).permit(:name, :description, :phone)
  end

  def current_user_store
    current_user.stores.find(params[:id])
  end

  def manager
    store = Store.find(params[:id])
    if current_user.id != store.user_id
      redirect_to root_url
    end
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_action :authenticate_user!
  before_action :manager

  def manager
    store = Store.find(params[:store_id])
    if current_user.id != store.user_id
      redirect_to root_url
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :load_cart
  before_action :authenticate_user!, except: [:new, :create]

  def index
    @orders = Order.where(:user_id => current_user.id)
    @orders = @orders.order(id: :DESC)

    if params[:order_search].present?
      @orders = @orders.where("(id) like ?", "%#{params[:order_search]}%")
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @products = @order.products
  end

  def new
    @order = Order.new
    @products = @cart.products
    @sum = @cart.sum
  end

  def create
    @products = @cart.products
    @sum = @cart.sum
    @payments = []

    unless user_signed_in?
      existing_users = User.where(:email => params[:order][:email])
      if existing_users == []
        user = create_user
        sign_in(user)
      else
        redirect_to new_user_session_path
        return
      end
    end

    @cart.stores.each do |store|
      order = create_order(store, current_user || user)

      unless order.save
        @order = order
        return render(:new, status: :unprocessable_entity)
      end
    end

    payment_ids = @payments.map do |payment|
      payment.id
    end

    @cart.clear_product

    redirect_to checkout_payments_path(:ids => payment_ids)
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to manager_store_order_path(@order.store_id, @order.id)
    else
      render :edit
    end
  end

  def vue_table
    @orders = Order.where(:user_id => current_user.id)
    respond_to do |format|
      format.html
      format.json { render :json => @orders.to_json }
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :last_name, :email, :address, :phone, :zip, :country, :status)
  end

  def create_order_product(product, order)
    order_product = OrderProduct.new(
      :product_id => product.id,
      :order_id => order.id
    )
    order_product.product_price = product.price - product.discount
    order_product.product_count = @cart.count(product.id.to_s)
    order_product.product_name = product.name
    order_product.product_image = product.images[0]
    order_product.save
  end

  def create_order(store, user)
    order = Order.new(order_params)
    order.user_id = user.id
    order.store_id = store.id
    order.sum_price = 0

    if order.save
      @cart.products.where(:store_id => store.id).each do |product|
        create_order_product(product, order)
      end

      sum_price = 0
      order.order_products.each do |product|
        sum_price += product.product_count * product.product_price
      end

      order.sum_price = sum_price

      if order.save
        payment = Payment.new(
          :order_id => order.id,
          :user_id => order.user_id
        )
        payment.save
        @payments << payment
      end
    end

    return order
  end

  def create_user
    user = User.create(
      name: params[:order][:name],
      email: params[:order][:email],
      phone: params[:order][:phone],
      password: "qwerty",
      password_confirmation: "qwerty"
    )
  end
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/manager/orders/_form.html.erb
<div class="bg-body-tertiary col-md-5 col-lg-4 order-md-last" style="border-radius:20px;background:#6d757d;">
  <%= form_for @order do |form| %>
    <div class="d-flex justify-content-between pt-2">
      <%= form.label :status %><br>
      <%= form.select :status, ["new", "in progress", "completed"], selected: "public", class:"mx-2" %>
    </div>
    <hr>
    <%= form.submit "Save changes ", class:"w-100 btn btn-primary btn-lg mb-2" %>
  <% end %>
</div>

app/views/manager/orders/index.html.erb
<main>
  <div class="row g-5">
    <div class="bg-body-tertiary col-md-5 col-lg-4 order-md-last" style="border-radius:20px;background:#6d757d;">    
      <div class="mt-3 list-group mb-3">

        <% if current_user %>
          <% if @store.user_id == current_user.id %>
            <%= link_to "Edit store", edit_manager_store_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Show all store product", manager_store_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Create a new product", new_manager_store_product_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Statistics", statistic_manager_store_orders_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Destroy store", manager_store_path(@store.id), data:{turbo_method: :delete}, class:"btn btn-outline-secondary" %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-7 col-lg-8">
      <div class="mb-5 text-center">
        <h4 class="mb-3 h2"><%= @store.name %> Orders</h4>
      </div>
      <% if @store.orders.count == 0 %><!--@store.store_new_orders == 0-->
        <p class="h2"> You don't have orders yet </p>
      <% else %>
        <div class="col-12 d-flex flex-column">

          <div class="d-flex row manager_tabs_wrap">
            <nav class="col-5">
              <ul class="nav nav-pills">
                <li class="nav-item">
                  <%= link_to "New", manager_store_orders_path(status: "new"), class:"nav-link  #{'active' if params[:status] == "new" || params[:status].nil?}" %>
                </li>
                <li class="nav-item admin_tab_item">
                  <%= link_to "In progress",manager_store_orders_path(status: "in progress"), class:"nav-link #{'active' if params[:status] == "in progress" }" %>
                </li>
                <li class="nav-item admin_tab_item">
                  <%= link_to "Completed",manager_store_orders_path(status: "completed"), class:"nav-link #{'active' if params[:status] == "completed" }" %>
                </li>
              </ul>
            </nav>
          </div>

          <div class="col-12 d-flex justify-content-between">
            <p class="col-1">
              №
            </p>
            <p class="col-2">
              Status
            </p>
            <p class="col-2">
              Price
            </p>
            <p class="col-4">
              Client email
            </p>
            <p class="col-2">
              Created at
            </p>
            <p class="col-1">
               status
            </p>
          </div>

          <%@orders.each do |order|%>
            <div class="col-12 d-flex justify-content-between bg-body-tertiary order_list">
              <p class="col-1 px-2"><%= link_to order.id, manager_store_order_path(order.store_id, order.id), id:"more_link" %></p>
              <p class="col-2"><%= order.status %></p>
              <p class="col-2"><%= number_to_currency(order.sum_price) %></p>
              <p class="col-4"><%= order.email %></p>
              <p class="col-2"><%= time_ago_in_words(order.created_at) %> <span>ago</span></p>
              <% if order.payment.status? %>
                <p class="col-1">paid</p>
              <% else %>
                <p class="col-1">not paid</p>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/manager/orders/show.html.erb
<main>
  <div class="py-5 text-center">
    <h4 class="mb-3 h2">Order №<%=@order.id%></h4>
  </div>
  <div class="row g-5">
    
    <div class="bg-body-tertiary col-md-5 col-lg-4 order-md-last" style="border-radius:20px;background:#6d757d;">
      <%= render "orders/form"%>
    </div>
    
    <div class="col-md-7 col-lg-8">
      
      <div class="col-12 d-flex flex-column">
        <div class="col-11 d-flex justify-content-between">
          <p class="col-3">
            Product name
          </p>
          <p class="col-1">
            Price
          </p>
          <p class="col-2">
            Count
          </p>
          <p class="col-2">
            Status
          </p>
          <p class="col-2">
            Payment status
          </p>
          <p class="col-1">
            sum
          </p>
        </div>

        <% @order_products.each do |order_product| %>
          <div class="col-11 d-flex justify-content-between bg-body-tertiary">
            <div class="text-body-secondary d-flex col-3 justify-content-between">
              <% if order_product.product %>
                <p class="col-3">
                  <img src= <%= order_product.product_image %> alt= "<%= order_product.product_name%>" class="manager_order_img" >
                </p>
              <% else %>
                <p class="col-4">
                  <%= image_tag("no_picture_image.png") %>
                </p>
              <% end %>
              <p class="col-8"><%= order_product.product_name %></p><br>
            </div>
            <p class="col-1">
              <%= order_product.product_price %>$
            </p>
            <p class="text-body-secondary col-2">
              <%= order_product.product_count %>
            </p>
            <p class="text-body-secondary col-2">
              <%= @order.status %>
            </p>
              <% if @order.payment.status? %>
                <p class="col-2">paid</p>
              <% else %>
                <p class="col-2">not paid</p>
              <% end %>
            <p class="col-1">
              <%= order_product.product_price * order_product.product_count %>$
            </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/manager/orders/statistic.html.erb
<main>
  <div class="row g-5">
    <div class="bg-body-tertiary col-md-5 col-lg-4 order-md-last" style="border-radius:20px;background:#6d757d;">    
      <div class="mt-3 list-group mb-3">

        <% if current_user %>
          <% if @store.user_id == current_user.id %>
            <%= link_to "Edit store", edit_manager_store_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Show all store product", manager_store_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Create a new product", new_manager_store_product_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Show orders", manager_store_orders_path(@store.id), class:"btn btn-outline-primary" %>
            <hr>
            <%= link_to "Destroy store", manager_store_path(@store.id), data:{turbo_method: :delete}, class:"btn btn-outline-secondary" %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-7 col-lg-8">
      <h1>
        Orders statistic
      </h1>
      <div class="statistic_chart_wrap">
        <canvas id="myChart" width="800px" height="500px" data-labels="<%= @data_keys %>" data-data="<%= @data_values %>"></canvas>
      </div>
  </div>
</main>