config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "help" => "pages#help"
  get "create_stor_info" => "pages#create_stor_info"
  get "cart/add" =>"cart#add"
  get "cart/delete" =>"cart#delete"
  get "cart/delete_all" => "cart#delete_all"
  get "cart/show" =>"cart#show"
  get "clear" => "cart#clear"
  get "elsearch" => "search#elsearch"

  resources :orders do
    collection do
      get "vue_table"
    end
  end

  resources :payments, only: [] do
    # member do payments/:id/foo
    #   get "foo"
    # end
    collection do #payments/foo
      get "checkout"
      get "successful"
      post "execute"
    end
  end

  resources :stores do
    resources :products do
      resources :reviews
    end
  end

  namespace :manager do
    resources :stores do
      resources :orders do
        collection do
          get "statistic"
        end
      end
      resources :products do
        collection do
          get "export"
          get "import"
          post "post_import"
        end
      end
    end

    resources :products, only: [:index]
  end

  namespace :api do
    resources :stores, only: [:index, :show] do
      get "products"
      resources :products, only: [:show] do
        # collection do
        #   get "store_products"
        # end
      end
    end
    resources :products, only: [:index]
  end

  resources :products, only: [:index]
  resources :users

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  belongs_to :store
  has_one :payment

  validates :name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :country, presence: true
  validates :zip, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  if ENV['ELASTICSEARCH_URL'].present?
    searchkick
  end

  belongs_to :store
  belongs_to :category
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :reviews

  mount_uploaders :images, ImageUploader
  serialize :images # , JSON  If you use SQLite, add this line.

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :discount, presence: true

  unless ENV['ELASTICSEARCH_URL'].present?
    def self.reindex
      nil
    end

    def self.search(query)
      where("lower(name) like ?", "%#{query.downcase}%")
    end
  end

  def price_with_discount
    price - discount
  end

  def calc_rating
    if reviews.count > 0
      (reviews.sum(:rating).to_f / reviews.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end

  after_update do
    store.update_rating
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  after_create do
    product.update_rating
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, :dependent => :destroy
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true, length: { minimum: 9 }

  def store_new_orders
    orders.where(:status => :new).count
  end

  def calc_rating
    if products.count > 0
      (products.sum(:rating) / products.count).round(1)
    else
      return 0
    end
  end

  def update_rating
    self.rating = calc_rating
    save
  end
end

app/models/store_user.rb
class StoreUser < ApplicationRecord
  belongs_to :user
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stores, :dependent => :destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create do
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.last(10)
    @stores = Store.all.last(5)
    @discount_products = Product.all.where(" discount > 0").last(8)
    @categories = Category.all
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_categories.html.erb
<div class="d-flex flex-column col-2">
  <h4 class="category_header">Category</h4>
  <% @categories.each do |category| %>
    <%= link_to category.name, products_path(category_id: category.id), class:"p-2" %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="d-flex justify-content-between col-12">

  <%= render "home/categories" %>

  <div class="d-flex flex-column col-10">
    <div class="col-12">
      <div class="d-flex justify-content-between col-4"> 
        <h3 > Last products </h3>
        <small> <%= link_to "All products", products_path, class:"btn btn-outline-secondary" %> </small>
      </div>
      <div class="row g-4 mt-1">
        <% @products.each do |product|%>
          <%= render product %>
        <% end %>
      </div>
    </div>

    <hr>

    <div class="d-flex justify-content-between col-4">
      <h3> Last stores </h3>
      <small> <%= link_to "All stores", stores_path, class:"btn btn-outline-secondary" %> </small>
    </div>

    <div class="col-12">
      <div class="row g-4 mt-1">
        <% @stores.each do |store| %>
          <%= render store %>
        <% end%>
      </div>
    </div>

    <hr>

    <div class="d-flex col-4"> 
      <h3>
        Last discount products
      </h3>
    </div>

    <div class="col-12">
      <div class="row g-4 mt-1">
        <% @discount_products.each do |discount_product|%>
          <%= render discount_product %>
        <% end%>
      </div>
    </div>
  </div>
</div>